### ISSUE TITLE
ownership

### ISSUE THREAD

**Issue by bengreenier** [trstringer/azure-chaos-fn-webapp-startstop#2]
@trstringer - want to transfer this to me or add me as a contributor? thinking that may may carrying this forward a touch easier from the ms side.

**Comment by Ethan-Arrowood** [comment]
If possible I'd like to be added as a contributor as well so I can keep this extension updated as we continue to develop platform-chaos SDK

**Comment by trstringer** [comment]
@bengreenier let me know your preference, and I'll set it!

**Comment by trstringer** [comment]
Done!
